### ISSUE TITLE
Fehler beheben

### ISSUE THREAD

**Issue by Finnomator** [Finnomator/CardNight#33]
### Witch (@TheCoderChris)
- [x] #34

### Ui (@Finnomator)
- [x] #35 
- [x] #42
- [x] #47
- [x] #62 
- [ ] Bilder im Hauptmenü strecken sich über die Fensterhöhe hinaus, wenn das Fenster zu breit gezogen wird
- [x] Umlaute werden nicht richtig dargestellt

### Sonstiges

**Comment by TheCoderChris** [comment]
Gegner legen nicht mehr Zauberer auf Zauberer, wenn sie eigentlich den Stich wollen.
