### ISSUE TITLE
Easter Eggs

### ISSUE THREAD

**Issue by Finnomator** [Finnomator/CardNight#51]
# Easter Eggs

Eine Sammlung an Easter Eggs, die implementiert werden könnten. Hauptsächlich bestehend aus alternativen Bildern von früheren Designs.

### Die Diebin

<img src="https://github.com/Finnomator/CardNight/blob/51-easter-eggs/src/main/resources/cardnight/alte-designs/Witch_1_gelb.png?raw=true" height="200">

- [x] Integriert

### Der Hexer als Gegner

Bei der [Tic Tac Toe Gegnerwahl](https://github.com/Finnomator/CardNight/blob/master/src/main/resources/cardnight/game-views/tictactoe/gegner-wahl.fxml) als alternatives Bild für den "Gegen einen Menschen" Button.

<img src="https://github.com/Finnomator/CardNight/blob/51-easter-eggs/src/main/resources/cardnight/alte-designs/IPS_Gegen_Mensch.png?raw=true" height="200">

- [x] Integriert

### Sound einstellen Sound

[Soundeinstellen_Sound.zip](https://github.com/Finnomator/CardNight/files/11749823/Soundeinstellen_Sound.zip)

- [x] Integriert

**Comment by ZweiWueste** [comment]
Ich liebe es! :)
